### ISSUE TITLE
logs folder permissions different 

### ISSUE THREAD

**Issue by jfmatth** [jcalazan/ansible-django-stack#121]
Hi, thank you so much for this repo, it's amazing and helping me move away from manual deployment of my django app - Helping where i can.

I noticed that after deployment, and this might be on purpose, but the LOGS folder has different permissions than others in the app, see below:

```
jfmatth@testing:/webapps/basicapp$ ll
total 44
drwxr-xr-x 9 basicapp webapps 4096 Jul 31 15:49 ./
drwxr-xr-x 3 root     root    4096 Jul 31 15:48 ../
drwxr-xr-x 5 basicapp webapps 4096 Jul 31 15:49 basicapp/
drwxr-xr-x 3 basicapp webapps 4096 Jul 31 15:48 bin/
drwxr-xr-x 2 basicapp webapps 4096 Jul 31 15:48 include/
drwxr-xr-x 3 basicapp webapps 4096 Jul 31 15:48 lib/
drwxrwxr-- 2 basicapp webapps 4096 Jul 31 15:49 logs/
-rw-rw-r-- 1 basicapp webapps  716 Jul 31 15:48 maintenance_off.html
-rw-r--r-- 1 basicapp webapps   61 Jul 31 15:48 pip-selfcheck.json
drwxr-xr-x 2 basicapp webapps 4096 Jul 31 15:49 run/
drwxr-xr-x 3 basicapp webapps 4096 Jul 31 15:48 share/
jfmatth@testing:/webapps/basicapp$  

```

Not sure where this is setup, and happy to fix and do a PR for you.

**Comment by YPCrumble** [comment]
@jfmatth I'm not 100% sure but isn't the difference giving any user in the `webapps` group write permissions to the logs? Currently in the repo all users are named `application_name` so this is redundant, but the current setting makes it possible to change the celery or rabbitmq user to another name and still be able to write to the logs directory. What do you think?

**Comment by jfmatth** [comment]
@YPCrumble Understood, just wanted to point it out and make sure you're aware of difference
