### ISSUE TITLE
Question - DB_host variable

### ISSUE THREAD

**Issue by jfmatth** [jcalazan/ansible-django-stack#122]
Hi,

Are there any plans (or is it there already) for a DB_HOST variable?

Thanks,

J

**Comment by YPCrumble** [comment]
@jfmatth currently there is not. The db role adds a local database so the host should be set to localhost like so:

```
        'HOST': '127.0.0.1',
        'PORT': '5432',
```

You could also set your own DB_HOST parameter in the `django_environment` section here if you want to use an external database: https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/defaults/main.yml#L29

**Comment by jfmatth** [comment]
@YPCrumble Thanks for the reply, and I'll work with what's there now.

One other question, how does the maintenance page work?  I noticed that too, looks super cool

Also, I may add some docs to use this for a basic / tutorial install.  There are some approaches that you take that are different from the django tutorial that threw me off, that I think people could use some guidance on.

this is a great project, thanks again.

**Comment by YPCrumble** [comment]
@jfmatth I haven't used it recently but I believe if you copy `maintenance.html` to `webapps/[application_name]/[application_name]/maintenance_on.html` the maintenance page should work automatically. You might have to restart NGINX.

Ideally I suppose we should have a playbook variable for turning the maintenance page on or off - maybe as part of the `deploy` tag.

Any docs or tutorial would be welcome! I've always thought that #93 would be helpful in improving the visibility of this repo. A tutorial would be fantastic as well!

**Comment by jfmatth** [comment]
@YPCrumble thanks for the update. 

In running through your repo and getting it to work, i found some areas that could use better docs, and i'll see if i can put those into a PR.

I'm planning on making it work with my simple django app, and take my lesson's learned from that to make a tutorial for your repo :)

thanks again for publishing this, it's great!
