### ISSUE TITLE
Failure in web task run directory creation

### ISSUE THREAD

**Issue by jpmjpmjpm** [jcalazan/ansible-django-stack#144]
In `web` tasks playbook, the settings of application file permissions comes after the setup of the supervisor:
```
...
- include: setup_django_app.yml
  tags: deploy

- include: setup_supervisor.yml
  tags: supervisor

- include: set_file_permissions.yml
  tags: deploy
```

This can lead to a failure at `run directory` creation in the [gunicorn_start](https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/templates/gunicorn_start.j2) script. Namely:

```
# Create the run directory if it doesn't exist.
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
```
**For the correction, I propose to move the `set_file_permissions` task before `setup_supervisor` in [web tasks playbook](https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/tasks/main.yml), like**:

```
---

- include: install_additional_packages.yml
  tags: packages

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_git_repo.yml
  tags: deploy

- include: setup_react_app.yml
  tags: deploy

- include: setup_django_app.yml
  tags: deploy

- include: set_file_permissions.yml
  tags: deploy

- include: setup_supervisor.yml
  tags: supervisor
```

Let me know if that makes sense. I don't have in mind a potential negative impact.

**Comment by YPCrumble** [comment]
@jpmjpmjpm thanks for the suggestion! I ran into the same issue actually and have that change as part of my personal fork.

The issue has also occurred with `setup_virtualenv` and `setup_git_repo` in some environments - would you mind moving it to just after `create_users_and_groups` in your PR?
