### ISSUE TITLE
Clean .pyc files after pulling latest code

### ISSUE THREAD

**Issue by jcalazan** [jcalazan/ansible-django-stack#16]
This is useful during those times when you deleted a package and the remaining .pyc files could break the app.

A good spot to do this is right after pulling the latest code from the git repo.

`find . -name “*.pyc” -delete`

**Comment by chrifey** [comment]
I also just discovered this. Since new ONTAP Versions ship with HTTP disabled by default (only HTTPS active, which is good) a lot of users that start using it will run into this.
