### ISSUE TITLE
Help with usage on multiple servers

### ISSUE THREAD

**Issue by hnarayanan** [jcalazan/ansible-django-stack#19]
*This is more of a question on how to use this project rather than a specific issue.*

This playbook works great on a local Vagrant VM but I'm not sure how to use it on a cloud provider[1]. Here is what I've tried:

- I setup four servers: `webserver-1`, `webserver-2`, `dbserver`, and `memcachedserver` (mirroring the server inventory in `local`)
- I created an inventory file called `development` which pointed to these 4 servers under the appropriate sections
- I ran: `ansible-playbook -i development -v development.yml`

As it's running, I notice all roles being applied to all servers (and this seems to be reflected in `deployment.yml` that lists `hosts` as `all` and mentions all `roles`). How do I go about ensuring that only the base + appropriate role is applied to the relevant server? Or have I misunderstood this entirely?

And thank you for this excellent project, I've learnt quite a bit from it as I've been learning Ansible and using it for my own Django apps.

[1] I'm attempting this with Google Cloud, but that's not relevant to the question.

**Comment by jcalazan** [comment]
Hey Arish,

I'm refactoring this project to make it more suitable for what you're trying to do, see this branch (it's almost done, I just need to test it and update the docs, will probably merge this weekend): https://github.com/jcalazan/ansible-django-stack/tree/refactor

Here's the ticket that kinda explains the changes: https://github.com/jcalazan/ansible-django-stack/issues/17

**Comment by jcalazan** [comment]
An example scenario here:

- `development` inventory file - with sections for `webservers` and `dbservers`
- `site.yml` - Your entire site/environment, say `webservers` and `dbservers`, which includes 2 sub-playbooks: `webservers.yml` (where `host:` is set to only those servers in the `webservers` section from the `development` inventory file), `dbservers.yml` (where `host:` is set just for `dbservers`)

To provision the entire site consisting of web servers and database servers:

```
ansible-playbook -i development site.yml
```

To provision just web servers:

```
ansible-playbook -i development webservers.yml
```

To provision just database servers:

```
ansible-playbook -i development dbservers.yml
```

Also note that in the `development` inventory file, I also have an `all:vars` section there which basically just creates a variable I can use in the playbook and will apply to `all` hosts.  In this case, I set a var called `env` with a value of `dev`, which I then use in the playbook to decide which `env_vars` file to use.

So if I have a `production` inventory file, for example, I would set the `all:vars` section to env=prod, so the playbook will then use the `env_vars/prod.yml` file if I pass in `-i production`.

Hope that makes sense!

**Comment by hnarayanan** [comment]
Thank you so very much for the explanation. This made a lot of sense, and the bit of insight I was missing is that different (sub)playbooks could point to different server inventories.

I will test this after you've completed your work and merge into master, and hopefully contribute a useful changeset or two after that. :)
