### ISSUE TITLE
Trouble with Django collectstatic

### ISSUE THREAD

**Issue by arcadiy** [jcalazan/ansible-django-stack#28]
Hi there,

Thank you for making this thorough playbook available. It's been an incredible asset as I've figured out how to deploy a Django app.

I am, however, having an issue: the "Run Django collectstatic" task in the playbook continues to fail with the error: 

```
You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```

It seems like an intuitive enough error message, but I can't seem to diagnose the problem:
- My STATIC_ROOT variable is defined exactly the way it is in your repo:   
  
  STATIC_ROOT: "{{ nginx_static_dir }}"
- I added a task as follows to sanity check that the env variable is set:

``` yml
   - name: Sanity check env vars
   shell: echo $STATIC_ROOT
   environment: django_environment
```

That task correctly outputs the path "/webapps/appname/static/"
- I even modified manage.py to output the env variable so it definitely knows that it's set and what it's set to. This (again) returns the correct path as expected.
- Finally, I tried setting the variable in my Django settings file instead. If I do that, then the collectstatic command works correctly and my static resources are loaded correctly.

At this point, I'm totally stumped on why I get the error message when I use the playbook configuration as opposed to setting this env variable in the Django settings directly; I can only assume the error message Django is returning is incorrect, but I don't know why.

Any ideas?

**Comment by jcalazan** [comment]
Hey @arcadiy ,

That error message looks like a Django error.  So I believe you need to set the STATIC_ROOT setting in your Django settings file (example: https://github.com/jcalazan/youtube-audio-dl/blob/master/youtubeadl/settings/base.py#L124-L125).
