### ISSUE TITLE
wrong wsgi path

### ISSUE THREAD

**Issue by nileshbits** [jcalazan/ansible-django-stack#29]
In ansible-django-stack/roles/web/templates/gunicorn_start.j2, according to the README directory structure, shouldn't the last line:  {{ application_name }}.wsgi be {{ project_name }}.wsgi? (since wsgi is in project path, not apps dir)

**Comment by jcalazan** [comment]
Hey nileshbits, it does seem confusing and I should update the readme.  I should've called the second `myproject` in the tree `myapplication`.  The first `myproject` is the git project root, the second one is the main Django app, and the `apps` dir is for the sub-applications with their own views/models/urls.

I'll add to my to do list to update this.  Thanks for pointing it out!

**Comment by nileshbits** [comment]
Great! By the way, great job on providing this playbook... saved me tons of time!

**Comment by jcalazan** [comment]
Np nileshbits!  Glad you found it useful :)

**Comment by LennyLip** [comment]
@jcalazan , hm, i don't understand. "Note that the default values in the playbooks assume that your project structure looks something like this:
├── myapp
│   ├── apps
│   │   └── __init__.py
│   ├── __init__.py
│   ├── urls.py
│   └── wsgi.py"

but start

{{ application_name }}.wsgi
