### ISSUE TITLE
Fatal: {'msg': "One or more undefined variables: 'omit' is undefined", 'failed': True}

### ISSUE THREAD

**Issue by cloud-rocket** [jcalazan/ansible-django-stack#30]
Any ideas what might be causing it?

```
==> default: TASK: [web | Create the virtualenv postactivate script to set environment variables] ***
==> default: fatal: [localhost] => {'msg': "One or more undefined variables: 'omit' is undefined", 'failed': True}
==> default: fatal: [localhost] => {'msg': "One or more undefined variables: 'omit' is undefined", 'failed': True}
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
```

Tanx

**Comment by jcalazan** [comment]
Hey Meir,

What version of Ansible are you using?

Seems to be coming from here: https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/vars/main.yml#L33-L36

If you don't use those env vars in your project you can probably just also delete them.

**Comment by cloud-rocket** [comment]
Ansible 1.5.4 (from Ubuntu 14.04 repo )....

Should I upgrade to later?

**Comment by jcalazan** [comment]
Ah yes, the `omit` option I believe was introduced in Ansible 1.8.  I'm currently on 1.9.4 and working fine for me.

**Comment by cloud-rocket** [comment]
tanx!
