### ISSUE TITLE
Install Supervisor

### ISSUE THREAD

**Issue by LennyLip** [jcalazan/ansible-django-stack#32]
I think, "Install Supervisor" task must not to be in celery role.
I don't use celery, and got error when config gunicorn with supervisor, because supervisor is not installed.

may be it must place in base or seprate role?

**Comment by jcalazan** [comment]
Hi Lenny,

Can you post the error message?

**Comment by jcalazan** [comment]
Oh, also make sure `celery` is not included in your playbook if your app doesn't use it.

Example: https://github.com/jcalazan/ansible-django-stack/blob/master/vagrant.yml#L20

**Comment by LennyLip** [comment]
@jcalazan i already delete logs and rewrite tasks.

If we don't use celereny, Install Supervisor task is not being run.

https://github.com/jcalazan/ansible-django-stack/blob/master/roles/celery/tasks/setup_supervisor.yml

   - name: Install Supervisor
     apt: name=supervisor update_cache={{ update_apt_cache }} state=installed
     tags:
       - celery


but in the web role we config and restart supervisor service, which currently is not installed:

https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/tasks/setup_supervisor.yml

   - name: Re-read the Supervisor config files
     supervisorctl: name={{ application_name }} state=present

   - name: Restart Supervisor
     supervisorctl: name={{ application_name }} state=restarted

**Comment by jcalazan** [comment]
Ah, I see what you mean.

It is actually in the `base` role: https://github.com/jcalazan/ansible-django-stack/blob/master/roles/base/tasks/main.yml#L27

**Comment by LennyLip** [comment]
Ops, sorry, my bad!
I've been comment this line :rotating_light: 
Thank you!

**Comment by jcalazan** [comment]
Np Lenny, I probably should actually remove the install supervisor in the celery role, thanks for pointing that out!
