### ISSUE TITLE
DATABASE_NAME ?

### ISSUE THREAD

**Issue by LennyLip** [jcalazan/ansible-django-stack#34]
https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/vars/main.yml#L31

```
DATABASE_USER: "{{ db_user }}"
DATABASE_PASSWORD: "{{ db_password }}"
```

may be, we need to add

DATABASE_NAME: "{{ db_name }}"

?

**Comment by foozmeat** [comment]
I use `DATABASE_NAME: "{{ db_user }}"`

**Comment by LennyLip** [comment]
@foozmeat yep, me too. But ansible-django-stack need is set its too.
