### ISSUE TITLE
User of nginx?

### ISSUE THREAD

**Issue by LennyLip** [jcalazan/ansible-django-stack#37]
Currently user of nginx is default:

f.e. debian nginx.conf:
user = www-data

So, when nginx try to access 500.html

2016/01/18 13:02:09 [error] 10841#0: *12 open() "/srv/myapp/app-project/myapp/templates/500.html" failed (13: Permission denied)

May be we must change nginx user to
user = {{gunicorn_user}}

?

**Comment by jcalazan** [comment]
@LennyLip This is probably way late now, but that file should have global read permission.
