### ISSUE TITLE
ERROR! environment must be a dictionary, received django_environment

### ISSUE THREAD

**Issue by capooti** [jcalazan/ansible-django-stack#38]
I am using ansible 2.0.0.2, and I am receiving this error during provisioning:

TASK [web : Run Django database migrations] ************************************
[DEPRECATION WARNING]: Using bare variables for environment is deprecated. 
Update your playbooks so that the environment value uses the full variable 
syntax ('{{foo}}'). This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
fatal: [default]: FAILED! => {"failed": true, "msg": "ERROR! environment must be a dictionary, received django_environment (<class 'ansible.parsing.yaml.objects.AnsibleUnicode'>)"}

**Comment by jcalazan** [comment]
Lots of changes in 2.0, haven't tried it out yet.  Will see if I'll have time this weekend to take a look, for the time being please use Ansible version < 2.0.

Thanks for reporting this!

**Comment by capooti** [comment]
thanks, I have fixed it changing this:

environment: django_environment

to this:

environment: "{{ django_environment }}"

as suggested in the warning.

**Comment by jcalazan** [comment]
@capooti Applied your fix.  Thank you!
