### ISSUE TITLE
Kill Apache httpd if already running?

### ISSUE THREAD

**Issue by stephenfin** [jcalazan/ansible-django-stack#40]
I "stacked" both the `db` and `web` roles on an Ubuntu 14.04 installation. On browsing to the IP address of the board, I noticed that Apache served the page instead of nginx. I killed the Apache service and restarted the nginx server and all was OK (well, mostly - more on that in another issue).

I don't know if a running Apache instance is the default on all Ubuntu installations or if it was just my particular instance, but checking for any running services that may conflict with our installation (i.e. ports 80, 443) sounds like a good thing.

**Comment by LennyLip** [comment]
When i install debian (not ubuntu), i have a choice to install software pack to install:
![Image of debian](http://www.linuxjournal.com/ufiles/debian_netinstall.png)

I think, you must disable "Web server" and "SQL Database" to run ansible-django-stack after (not shure for ubuntu, but we must "clean" system to run).

I think is not ansible-django-stack issue.

**Comment by jcalazan** [comment]
@stephenfin I'm pretty sure Apache is not installed by default at least in the base server image of Ubuntu.  Feels a bit of an edge case to me and the base image that should be used with this playbook shouldn't have Apache installed, so I'm closing this issue for now.
