### ISSUE TITLE
Provide guidance on `settings.py` values

### ISSUE THREAD

**Issue by stephenfin** [jcalazan/ansible-django-stack#41]
After resolving #40, I was able to load the page. However, I noticed that no CSS files had been loaded. This was because I had defined `STATIC_ROOT` in my `settings.py` file and the value differed from the location used in configuring nginx. It would be good to provide a little guidance about which variables should/shouldn't be declared in settings.

An alternative would be to parse the value in the provided settings file, but this would obviously involve a lot more work.

**Comment by stephenfin** [comment]
This is similar to #28

**Comment by LennyLip** [comment]
@stephenfin please, close issue, while it duplicate
