### ISSUE TITLE
Maintenance template incorrectly named?

### ISSUE THREAD

**Issue by philgyford** [jcalazan/ansible-django-stack#42]
I haven't used the playbook directly, but it's been incredibly useful to learn from.

I _think_ there's an inconsistency with naming... 

The [nginx_site_config.j2](https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/templates/nginx_site_config.j2) template refers to `{{ virtualenv_path }}/maintenance_on.html`.

But the [setup_virtualenv](https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/tasks/setup_virtualenv.yml) task moves the [maintenance_off.html](https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/templates/maintenance_off.html) template to `{{ virtualenv_path }}/maintenance_off.html`.

Should the latter task use maintenance_ON rather than OFF?

Or have I misunderstood?

**Comment by philgyford** [comment]
Only minutes later and I realise! You'd rename the `maintenance_off.html` file to `maintenance_on.html` in order to put the site in maintenance mode. OK, as you were!

**Comment by jcalazan** [comment]
:)
