### ISSUE TITLE
ssl_key_password isn't used anywhere

### ISSUE THREAD

**Issue by glassresistor** [jcalazan/ansible-django-stack#43]
In the env_vars files there is a variable called ssl_key_password but I can't figure out what it does.
I've been looking through the rest of the files(grepping for ssl_key_password) and I can't find it in use anywhere.
Is it actually required?

**Comment by jcalazan** [comment]
Hey @glassresistor, you're right, it's no longer used.  Will remove it, thanks for the heads up!
