### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by andymj** [jcalazan/ansible-django-stack#57]
Hi,

I got an issue on:

`TASK [web : Install packages required by the Django app inside virtualenv] *****
task path: /Users/username/vagrant/ansible-django-stack/roles/web/tasks/setup_django_app.yml:3
fatal: [default]: FAILED! => {"changed": false, "cmd": "/webapps/testdjango/bin/pip install -r /webapps/testdjango/test-django/requirements.txt", "failed": true, "msg": "\n:stderr: Could not open requirements file: [Errno 2] No such file or directory: '/webapps/testdjango/test-django/requirements.txt'\n"}`

by the way thank you for providing the set up.

**Comment by DavidCain** [comment]
Just looking at the error message... It seems your Django app doesn't have a `requirements.txt` file. You should add one.

**Comment by andymj** [comment]
@DavidCain so basically how do I provide this file, on my github repo?, what I did is I forked this repo and changed the git repo, name of project and name of app, under env_vars->base.yml file (didn't add ssl_.. keys) and run vagrant up, and got this issue of the requirements.txt file didn't exist. But then I clone the repo again to another folder, and didn't do any changes and just run vagrant up, and it worked. but I don't want to use defaults env_vars->base.yml settings. 

Sorry for the questions but I'm new to Django and ansible too.

**Comment by DavidCain** [comment]
To "provide the file" you just need to create a requirements file (see the [docs][docs]), commit and push to your repository. When you re-run Ansible (via Vagrant or otherwise), pip will pick up the requirements file and install the packages within to a virtual environment.

[docs]: https://pip.pypa.io/en/stable/user_guide/#requirements-files

**Comment by andymj** [comment]
Got it, thank you so much.
