### ISSUE TITLE
Include periodic PostgreSQL backup and restore scripts

### ISSUE THREAD

**Issue by YPCrumble** [jcalazan/ansible-django-stack#60]
@jcalazan have you considered adding backup and restore scripts? In particular one that also cleans the backup directory so that it doesn't become too large would be ideal. Let me know if helpful to add a PR? I'm not sure what your perspective on having too many roles in this ansible playbook is. I'm interested in adding various tasks that I use on my personal projects to have community code review and make sure I'm not doing anything silly :).

**Comment by jcalazan** [comment]
@YPCrumble I've thought about this a while back and decided to just leave it to the user as the way someone does the back up could really vary (such as naming of backup files, scheduling, how many copies to keep, whether to send a copy to Amazon S3/Dropbox/Google Drive, etc.)

**Comment by YPCrumble** [comment]
@jcalazan sounds good, closing.
