### ISSUE TITLE
How do you redirect www traffic to non-www?

### ISSUE THREAD

**Issue by YPCrumble** [jcalazan/ansible-django-stack#61]
Usually I use a slightly modified nginx.conf like [the last example in this stackoverflow answer](http://stackoverflow.com/a/11733363/2532070). This way nginx redirects to https _and_ the non-www version of my url.

Do you do something different, i.e., maybe using a CNAME DNS record? I'm not sure what the best approach is - would love to hear your opinion. I'd also be happy to submit a PR for a modified nginx.conf that includes the redirect to non-www (or perhaps either way with a flag) if that's helpful.

**Comment by jcalazan** [comment]
Hmm...in my case I do the complete opposite, basically redirecting non-www to www.

I do something like this (not sure if this is the best way):

```
### DOMAIN REDIRECTS ###

# Redirect nonwww toplevel domain to www
server {
        listen 80;
        listen 443;
        server_name example.com;
        return 301 https://www.example.com$request_uri;
}
```

For now let's leave this one alone as I'm not so sure many users would want this behavior.

**Comment by YPCrumble** [comment]
@jcalazan makes sense - closing this issue.

**Comment by captainjackrana** [comment]
I've created a simple hapi plugin for this. You can find it here:
https://github.com/captainjackrana/hapi-gate

**Comment by YPCrumble** [comment]
@jcalazan one small thing to note is that the certbot role also only works for either www or non-www. You have to add `-d www.{{ inventory_hostname }}` (or the reverse for non-www to www) to work with both versions.
