### ISSUE TITLE
Provide option to install Python 3 in virtualenv

### ISSUE THREAD

**Issue by jcalazan** [jcalazan/ansible-django-stack#62]
Add a var with a default value of `python2.7` and can be replaced with `python3`.

```
# roles/web/defaults.yml
virtualenv_python_version: python2.7
```

In the task the create the virutalenv:

```
virtualenv -p {{ virtualenv_python_version }} {{ virtualenv_path }} --no-site-packages
```

**Comment by hesamd** [comment]
In base you were updating pip, I guess the same should apply to pip3, shouldn't it?

**Comment by jcalazan** [comment]
I believe the `-p` in the virtualenv will take care of this.  So if you do something like `virtualenv -p python3 myenv`, the `pip` installer in the virtualenv will install the python3 versions of the packages.
