### ISSUE TITLE
Supporting Ubuntu 16.04

### ISSUE THREAD

**Issue by hesamd** [jcalazan/ansible-django-stack#64]
I tried hard to make the playbook working with Ubuntu 16.04, but Gunicorn wasn't cooperating and I couldn't figure it the problem from log. It will be nice if someone can give it a shot. One tiny advantage is that 16.04 is LTS and it comes with Python 3.5 by default.

**Comment by jcalazan** [comment]
@hesamd Can you post the error message from Gunicorn if any?

I don't plan to upgrade my servers to 16.04 until next year, but would be interested as well to see if anyone can get the playbook working with 16.04.

**Comment by mprat** [comment]
I've used subsets of this playbook on 16.04 (both vagrant and AWS without vagrant); I can submit a PR that attempts to solve some issues.
