### ISSUE TITLE
Allow user to specify exact python version to use in the virtualenv

### ISSUE THREAD

**Issue by YPCrumble** [jcalazan/ansible-django-stack#74]
I'm using a repo that needs a version of python after 2.7.9. I have a workaround to keep using 2.7.6 but thinking of providing a way for the user to specify exactly the python version to use.

@jcalazan one option would be rather than having the `use_python3` boolean, to change the repo to accept a specific python version to install and activate in the virtualenv. Any thoughts on the best way to proceed?

**Comment by mprat** [comment]
Can't you use this to specify the exact version you need? https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/defaults/main.yml

**Comment by YPCrumble** [comment]
@mprat virtualenv can only use versions of Python that are installed on the machine. Ubuntu 14.04 ships with only 2.7.6, so inputting python2.7.13 raises an error.

**Comment by mprat** [comment]
But you can install that version of Python by downloading a deb file / etc. and then including that specific version?

**Comment by YPCrumble** [comment]
Correct - I'm suggesting a PR that does exactly that without having to do it manually each time I configure the server.

**Comment by dpward** [comment]
@YPCrumble Can this issue be closed? I don't think it's possible to do this without re-building a specific Python version from the source code, which would seem well outside the scope of this playbook.
