### ISSUE TITLE
Missing definition template0

### ISSUE THREAD

**Issue by physicalattraction** [jcalazan/ansible-django-stack#81]
I see in task `postgresql_db` the option `template='template0'`, but there is no `template0` defined anywhere.

Solution would be to provide a template, but I wouldn't know which template would be general purpose enough, or to remove this option.

**Comment by YPCrumble** [comment]
`template0` is a [standard PostgreSQL template](
https://www.postgresql.org/docs/current/static/manage-ag-templatedbs.html).
What version of PostgreSQL are you running and what's the error you're
getting?

**Comment by physicalattraction** [comment]
I see now. I am not getting an error, the Ansible output says the db is created successfully, but then it is not created. :-s

**Comment by YPCrumble** [comment]
@physicalattraction let me know if you're still experiencing this issue? Closing for now but happy to re-open it.

**Comment by physicalattraction** [comment]
I haven't tried it for a while. Once the database is created, there aren't any issues. I think we manually created the database of the last microservice that we deployed using this stack.
