### ISSUE TITLE
MacOs installation

### ISSUE THREAD

**Issue by Shrhawk** [jcalazan/ansible-django-stack#82]
using the command:
`vagrant up`
or
`vagrant up --provider=docker
`

Showing following error:
"**rsync**" was not detected as installed in your guest machine. This
is required for rsync synced folders to work. In addition to this,
Vagrant doesn't know how to automatically install rsync for your
machine, so you must do this manually.

Kindly guide to fix this issue.

**Comment by dpward** [comment]
Are you using the [current version of Vagrant](https://www.vagrantup.com/downloads.html)?

Does this happen with an unmodified [Vagrantfile](Vagrantfile), or did you uncomment the line to configure synced folders?

**Comment by Shrhawk** [comment]
**Vagrant 1.8.7** and did'nt change anything @dpward

**Comment by Shrhawk** [comment]
@dpward the issue is resolved by updating the vagrant Thankyou :).Its better to update the installation guide too.
