### ISSUE TITLE
Need to rename nginx template?

### ISSUE THREAD

**Issue by philgyford** [jcalazan/ansible-django-stack#86]
When setting up nginx, the "Create the Nginx configuration file" task looks for the `{{ application_name }}.j2` template. But this template is called `youtubeadl.j2` in this repo.

I'm not sure if this is just something that needs to be in the README ("Rename the `roles/nginx/templates/youtubeadl.j2` file so it matches your `application_name`") or, hopefully, if it's something that can be automated.

Does it need to be specific to the application?

**Comment by jcalazan** [comment]
Hey Phil,

It's just a sample project and it's there for demo purposes. You'll need to rename the references to it along with other project-specific vars in `env_vars/base.yml` to use with another project. 

Hope that clears things up.

**Comment by philgyford** [comment]
Thanks! I think because everything else was pretty seamless, mostly just involving changing vars, I was lulled into thinking it was more generic :) 

Thanks for your work on this - it's invaluable!
